### ISSUE TITLE
Reports display for helpdesk

### ISSUE THREAD

**Issue by BrightonCProvo** [Provo-City-School-District/help.provo.edu#1] opened 2023-06-22 21:08 UTC
Allow users to create reports page that can give display stats example: tickets open, tickets by user

**Comment by joshespi** [comment] 2023-11-13 16:31
I think this was a dupe of https://github.com/Provo-City-School-District/help.provo.edu/issues/56

**Closed** 2023-11-13 16:32 UTC
Labels: Required
